//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practicante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulante
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public int idGenero { get; set; }
        public int idEstadoCivil { get; set; }
        public System.DateTime fecNacimiento { get; set; }
        public int edad { get; set; }
        public int idTipoDoc { get; set; }
        public long numDoc { get; set; }
        public long telefono { get; set; }
        public long celular { get; set; }
        public string pais { get; set; }
        public int idciudad { get; set; }
        public string direccion { get; set; }
        public string correo { get; set; }
        public int idestudios { get; set; }
        public int idcarrera { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        public virtual Estudio Estudio { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual TipoDoc TipoDoc { get; set; }
    }
}
